--         :ok_hand:         --

local fehax = Instance.new("ScreenGui")
local haxxframe = Instance.new("Frame")
local title = Instance.new("TextLabel")
local main = Instance.new("Frame")
local plr = Instance.new("TextBox")
local kill = Instance.new("TextButton")
local punish = Instance.new("TextButton")
local spambricks = Instance.new("TextButton")
local teleport = Instance.new("TextButton")
local god = Instance.new("TextButton")
local glitchy = Instance.new("TextButton")

fehax.Name = "fehax"
fehax.Parent = game.CoreGui

haxxframe.Name = "haxxframe"
haxxframe.Parent = fehax
haxxframe.Active = true
haxxframe.BackgroundColor3 = Color3.new(0.317647, 0.317647, 0.317647)
haxxframe.BorderSizePixel = 0
haxxframe.Draggable = true
haxxframe.Position = UDim2.new(0.232673272, 0, 0.43832022, 0)
haxxframe.Size = UDim2.new(0, 388, 0, 21)

title.Name = "title"
title.Parent = haxxframe
title.BackgroundColor3 = Color3.new(0.776471, 0.776471, 0.776471)
title.BorderSizePixel = 0
title.Position = UDim2.new(0, 0, 9.5714283, 0)
title.Size = UDim2.new(0, 388, 0, 21)
title.Font = Enum.Font.Garamond
title.Text = "FE Haxx Gui v1.3"
title.TextScaled = true
title.TextSize = 14
title.TextWrapped = true

main.Name = "main"
main.Parent = haxxframe
main.BackgroundColor3 = Color3.new(0.317647, 0.317647, 0.317647)
main.BorderSizePixel = 0
main.Position = UDim2.new(0, 0, 1, 0)
main.Size = UDim2.new(0, 388, 0, 179)

plr.Name = "plr"
plr.Parent = main
plr.BackgroundColor3 = Color3.new(0.494118, 0.494118, 0.494118)
plr.BorderSizePixel = 0
plr.Position = UDim2.new(0.226775959, 0, 0.0545356646, 0)
plr.Size = UDim2.new(0, 200, 0, 30)
plr.Font = Enum.Font.Arcade
plr.Text = "Player Name"
plr.TextScaled = true
plr.TextSize = 14
plr.TextWrapped = true

kill.Name = "kill"
kill.Parent = main
kill.BackgroundColor3 = Color3.new(0.494118, 0.494118, 0.494118)
kill.BorderSizePixel = 0
kill.Position = UDim2.new(0.0229423698, 0, 0.284916192, 0)
kill.Size = UDim2.new(0, 112, 0, 27)
kill.Font = Enum.Font.SourceSansLight
kill.Text = "Kill"
kill.TextScaled = true
kill.TextSize = 14
kill.TextWrapped = true

punish.Name = "punish"
punish.Parent = main
punish.BackgroundColor3 = Color3.new(0.494118, 0.494118, 0.494118)
punish.BorderSizePixel = 0
punish.Position = UDim2.new(0.35643062, 0, 0.284916192, 0)
punish.Size = UDim2.new(0, 112, 0, 27)
punish.Font = Enum.Font.SourceSansLight
punish.Text = "Punish"
punish.TextScaled = true
punish.TextSize = 14
punish.TextWrapped = true

spambricks.Name = "spambricks"
spambricks.Parent = main
spambricks.BackgroundColor3 = Color3.new(0.494118, 0.494118, 0.494118)
spambricks.BorderSizePixel = 0
spambricks.Position = UDim2.new(0.677961767, 0, 0.284916192, 0)
spambricks.Size = UDim2.new(0, 112, 0, 27)
spambricks.Font = Enum.Font.SourceSansLight
spambricks.Text = "Spam Bricks"
spambricks.TextScaled = true
spambricks.TextSize = 14
spambricks.TextWrapped = true

teleport.Name = "teleport"
teleport.Parent = main
teleport.BackgroundColor3 = Color3.new(0.494118, 0.494118, 0.494118)
teleport.BorderSizePixel = 0
teleport.Position = UDim2.new(0.0233225822, 0, 0.491620123, 0)
teleport.Size = UDim2.new(0, 112, 0, 27)
teleport.Font = Enum.Font.SourceSansLight
teleport.Text = "Hat Meme"
teleport.TextScaled = true
teleport.TextSize = 14
teleport.TextWrapped = true

god.Name = "god"
god.Parent = main
god.BackgroundColor3 = Color3.new(0.494118, 0.494118, 0.494118)
god.BorderSizePixel = 0
god.Position = UDim2.new(0.355796814, 0, 0.491620123, 0)
god.Size = UDim2.new(0, 112, 0, 27)
god.Font = Enum.Font.SourceSansLight
god.Text = "God"
god.TextScaled = true
god.TextSize = 14
god.TextWrapped = true

glitchy.Name = "glitchy"
glitchy.Parent = main
glitchy.BackgroundColor3 = Color3.new(0.494118, 0.494118, 0.494118)
glitchy.BorderSizePixel = 0
glitchy.Position = UDim2.new(0.677961767, 0, 0.491620123, 0)
glitchy.Size = UDim2.new(0, 112, 0, 27)
glitchy.Font = Enum.Font.SourceSansLight
glitchy.Text = "Glitchy"
glitchy.TextScaled = true
glitchy.TextSize = 14
glitchy.TextWrapped = true

punish.MouseButton1Down:connect(function()
    game.Players[plr.Text].Character:Destroy()
end)

kill.MouseButton1Down:connect(function()
    for i,v in pairs(game.Players[plr.Text].Character:GetChildren()) do
        if v:IsA("BasePart") then
            v.Name = "ok"
        end
    end
end)

spambricks.MouseButton1Down:connect(function()
    local okoko = game.Players[plr.Text]
    
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    local a = Instance.new("Part",workspace)
    a.Position = okoko.Character.Head.Position
    a.Size = Vector3.new(math.random(1,3),math.random(1,3),math.random(1,3))
    wait()
    okoko.Character.Head:Destroy()
    okoko.Character.Torso:Destroy()
end)

glitchy.MouseButton1Down:connect(function()
    local ok = game.Players[plr.Text]
    
    for i=1,100 do
        wait(2)
        ok.Character.Humanoid:Destroy()
        wait(2)
        Instance.new("Humanoid",ok.Character)
    end
end)

god.MouseButton1Down:connect(function()
    game.Players[plr.Text].Character.Humanoid:Destroy()
    Instance.new("Humanoid",game.Players[plr.Text].Character)
end)

teleport.MouseButton1Down:connect(function()
    local a = game.Players[plr.Text]
    
    for i,x in pairs (a.Character:GetChildren()) do
        if x:IsA("Accessory") then
            for i=1,50 do
                local ok = x.Handle:Clone()
                ok.Parent = workspace
                ok.CanCollide = true
                ok.Position = a.Character.Head.Position + Vector3.new(0,6.5,-6)
            end
        end
    end
end)