game.Workspace.BasicCommand:FireServer(7, "Simon has been kicked for even existing in the first place, game now ending. Enjoy your stupid win, lmao.", 5.5, 1.5, true, "Pizza")
wait()
game.Workspace.BasicCommand:FireServer(7, "Simon has been kicked for even existing in the first place, game now ending. Enjoy your stupid win, lmao.", 5.5, 1.5, true, "Pizza")
wait()
game.Workspace.BasicCommand:FireServer(7, "Simon has been kicked for even existing in the first place, game now ending. Enjoy your stupid win, lmao.", 5.5, 1.5, true, "Pizza")
wait()
game.Workspace.BasicCommand:FireServer(7, "Simon has been kicked for even existing in the first place, game now ending. Enjoy your stupid win, lmao.", 5.5, 1.5, true, "Pizza")
wait()
game.Workspace.BasicCommand:FireServer(7, "Simon has been kicked for even existing in the first place, game now ending. Enjoy your stupid win, lmao.", 5.5, 1.5, true, "Pizza")
wait()
game.Workspace.BasicCommand:FireServer(7, "Simon has been kicked for even existing in the first place, game now ending. Enjoy your stupid win, lmao.", 5.5, 1.5, true, "Pizza")
wait()
game.Workspace.BasicCommand:FireServer(7, "Simon has been kicked for even existing in the first place, game now ending. Enjoy your stupid win, lmao.", 5.5, 1.5, true, "Pizza")
wait()
game.Workspace.BasicCommand:FireServer(7, "Simon has been kicked for even existing in the first place, game now ending. Enjoy your stupid win, lmao.", 5.5, 1.5, true, "Pizza")
wait()
game.Workspace.BasicCommand:FireServer(7, "Simon has been kicked for even existing in the first place, game now ending. Enjoy your stupid win, lmao.", 5.5, 1.5, true, "Pizza")
wait()
game.Workspace.BasicCommand:FireServer(7, "Simon has been kicked for even existing in the first place, game now ending. Enjoy your stupid win, lmao.", 5.5, 1.5, true, "Pizza")
wait()
game.Workspace.BasicCommand:FireServer(7, "Simon has been kicked for even existing in the first place, game now ending. Enjoy your stupid win, lmao.", 5.5, 1.5, true, "Pizza")
wait()
game.Workspace.BasicCommand:FireServer(7, "Simon has been kicked for even existing in the first place, game now ending. Enjoy your stupid win, lmao.", 5.5, 1.5, true, "Pizza")
wait()
game.Workspace.BasicCommand:FireServer(7, "Simon has been kicked for even existing in the first place, game now ending. Enjoy your stupid win, lmao.", 5.5, 1.5, true, "Pizza")
wait()
game.Workspace.BasicCommand:FireServer(7, "Simon has been kicked for even existing in the first place, game now ending. Enjoy your stupid win, lmao.", 5.5, 1.5, true, "Pizza")
wait()