for i = 0.2, 10000 do
-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
-- Remote Path: game:GetService("ReplicatedStorage").RemoteEvent
 
local A_1 = "UpStrength"
local Event = game:GetService("ReplicatedStorage").RemoteEvent
Event:FireServer(A_1)
end
