--Phantom Forces ESP V3 By RelentlessRaptor / !!!RelentlessRaptor#5709 on discord.
--Please credit me in any videos you use this in. Thanks.
wait(0.5)
plrs = nil
for _,p in pairs(game:GetChildren()) do
    if p.ClassName == ("Players") then
    plrs = p
    end
end
function tors(plr)
local fr = Instance.new("SurfaceGui",plr.Character.Torso)
local frf = Instance.new("Frame",fr)
fr.Face = "Front"
fr.AlwaysOnTop = true
frf.Size = UDim2.new(1,0,1,0)
frf.BorderSizePixel = 0
frf.BackgroundColor3 = Color3.new(1,0,0)
frf.BackgroundTransparency = 0.2
local ba = Instance.new("SurfaceGui",plr.Character.Torso)
local baf = Instance.new("Frame",ba)
ba.Face = "Back"
ba.AlwaysOnTop = true
baf.Size = UDim2.new(1,0,1,0)
baf.BorderSizePixel = 0
baf.BackgroundColor3 = Color3.new(1,0,0)
baf.BackgroundTransparency = 0.2 
local le = Instance.new("SurfaceGui",plr.Character.Torso)
local lef = Instance.new("Frame",le)
le.Face = "Left"
le.AlwaysOnTop = true
lef.Size = UDim2.new(1,0,1,0)
lef.BorderSizePixel = 0
lef.BackgroundColor3 = Color3.new(1,0,0)
lef.BackgroundTransparency = 0.2
local ri = Instance.new("SurfaceGui",plr.Character.Torso)
local rif = Instance.new("Frame",ri)
ri.Face = "Right"
ri.AlwaysOnTop = true
rif.Size = UDim2.new(1,0,1,0)
rif.BorderSizePixel = 0
rif.BackgroundColor3 = Color3.new(1,0,0)
rif.BackgroundTransparency = 0.2
local to = Instance.new("SurfaceGui",plr.Character.Torso)
local tof = Instance.new("Frame",to)
to.Face = "Top"
to.AlwaysOnTop = true
tof.Size = UDim2.new(1,0,1,0)
tof.BorderSizePixel = 0
tof.BackgroundColor3 = Color3.new(1,0,0)
tof.BackgroundTransparency = 0.2
local bo = Instance.new("SurfaceGui",plr.Character.Torso)
local bof = Instance.new("Frame",bo)
bo.Face = "Bottom"
bo.AlwaysOnTop = true
bof.Size = UDim2.new(1,0,1,0)
bof.BorderSizePixel = 0
bof.BackgroundColor3 = Color3.new(1,0,0)
bof.BackgroundTransparency = 0.2
end
function rightar(plr)
local fr = Instance.new("SurfaceGui",plr.Character["Right Arm"])
local frf = Instance.new("Frame",fr)
fr.Face = "Front"
fr.AlwaysOnTop = true
frf.Size = UDim2.new(1,0,1,0)
frf.BorderSizePixel = 0
frf.BackgroundColor3 = Color3.new(1,0,0)
frf.BackgroundTransparency = 0.2
local ba = Instance.new("SurfaceGui",plr.Character["Right Arm"])
local baf = Instance.new("Frame",ba)
ba.Face = "Back"
ba.AlwaysOnTop = true
baf.Size = UDim2.new(1,0,1,0)
baf.BorderSizePixel = 0
baf.BackgroundColor3 = Color3.new(1,0,0)
baf.BackgroundTransparency = 0.2 
local le = Instance.new("SurfaceGui",plr.Character["Right Arm"])
local lef = Instance.new("Frame",le)
le.Face = "Left"
le.AlwaysOnTop = true
lef.Size = UDim2.new(1,0,1,0)
lef.BorderSizePixel = 0
lef.BackgroundColor3 = Color3.new(1,0,0)
lef.BackgroundTransparency = 0.2
local ri = Instance.new("SurfaceGui",plr.Character["Right Arm"])
local rif = Instance.new("Frame",ri)
ri.Face = "Right"
ri.AlwaysOnTop = true
rif.Size = UDim2.new(1,0,1,0)
rif.BorderSizePixel = 0
rif.BackgroundColor3 = Color3.new(1,0,0)
rif.BackgroundTransparency = 0.2
local to = Instance.new("SurfaceGui",plr.Character["Right Arm"])
local tof = Instance.new("Frame",to)
to.Face = "Top"
to.AlwaysOnTop = true
tof.Size = UDim2.new(1,0,1,0)
tof.BorderSizePixel = 0
tof.BackgroundColor3 = Color3.new(1,0,0)
tof.BackgroundTransparency = 0.2
local bo = Instance.new("SurfaceGui",plr.Character["Right Arm"])
local bof = Instance.new("Frame",bo)
bo.Face = "Bottom"
bo.AlwaysOnTop = true
bof.Size = UDim2.new(1,0,1,0)
bof.BorderSizePixel = 0
bof.BackgroundColor3 = Color3.new(1,0,0)
bof.BackgroundTransparency = 0.2
end
function leftar(plr)
local fr = Instance.new("SurfaceGui",plr.Character["Left Arm"])
local frf = Instance.new("Frame",fr)
fr.Face = "Front"
fr.AlwaysOnTop = true
frf.Size = UDim2.new(1,0,1,0)
frf.BorderSizePixel = 0
frf.BackgroundColor3 = Color3.new(1,0,0)
frf.BackgroundTransparency = 0.2
local ba = Instance.new("SurfaceGui",plr.Character["Left Arm"])
local baf = Instance.new("Frame",ba)
ba.Face = "Back"
ba.AlwaysOnTop = true
baf.Size = UDim2.new(1,0,1,0)
baf.BorderSizePixel = 0
baf.BackgroundColor3 = Color3.new(1,0,0)
baf.BackgroundTransparency = 0.2 
local le = Instance.new("SurfaceGui",plr.Character["Left Arm"])
local lef = Instance.new("Frame",le)
le.Face = "Left"
le.AlwaysOnTop = true
lef.Size = UDim2.new(1,0,1,0)
lef.BorderSizePixel = 0
lef.BackgroundColor3 = Color3.new(1,0,0)
lef.BackgroundTransparency = 0.2
local ri = Instance.new("SurfaceGui",plr.Character["Left Arm"])
local rif = Instance.new("Frame",ri)
ri.Face = "Right"
ri.AlwaysOnTop = true
rif.Size = UDim2.new(1,0,1,0)
rif.BorderSizePixel = 0
rif.BackgroundColor3 = Color3.new(1,0,0)
rif.BackgroundTransparency = 0.2
local to = Instance.new("SurfaceGui",plr.Character["Left Arm"])
local tof = Instance.new("Frame",to)
to.Face = "Top"
to.AlwaysOnTop = true
tof.Size = UDim2.new(1,0,1,0)
tof.BorderSizePixel = 0
tof.BackgroundColor3 = Color3.new(1,0,0)
tof.BackgroundTransparency = 0.2
local bo = Instance.new("SurfaceGui",plr.Character["Left Arm"])
local bof = Instance.new("Frame",bo)
bo.Face = "Bottom"
bo.AlwaysOnTop = true
bof.Size = UDim2.new(1,0,1,0)
bof.BorderSizePixel = 0
bof.BackgroundColor3 = Color3.new(1,0,0)
bof.BackgroundTransparency = 0.2
end
function leftle(plr)
local fr = Instance.new("SurfaceGui",plr.Character["Left Leg"])
local frf = Instance.new("Frame",fr)
fr.Face = "Front"
fr.AlwaysOnTop = true
frf.Size = UDim2.new(1,0,1,0)
frf.BorderSizePixel = 0
frf.BackgroundColor3 = Color3.new(1,0,0)
frf.BackgroundTransparency = 0.2
local ba = Instance.new("SurfaceGui",plr.Character["Left Leg"])
local baf = Instance.new("Frame",ba)
ba.Face = "Back"
ba.AlwaysOnTop = true
baf.Size = UDim2.new(1,0,1,0)
baf.BorderSizePixel = 0
baf.BackgroundColor3 = Color3.new(1,0,0)
baf.BackgroundTransparency = 0.2 
local le = Instance.new("SurfaceGui",plr.Character["Left Leg"])
local lef = Instance.new("Frame",le)
le.Face = "Left"
le.AlwaysOnTop = true
lef.Size = UDim2.new(1,0,1,0)
lef.BorderSizePixel = 0
lef.BackgroundColor3 = Color3.new(1,0,0)
lef.BackgroundTransparency = 0.2
local ri = Instance.new("SurfaceGui",plr.Character["Left Leg"])
local rif = Instance.new("Frame",ri)
ri.Face = "Right"
ri.AlwaysOnTop = true
rif.Size = UDim2.new(1,0,1,0)
rif.BorderSizePixel = 0
rif.BackgroundColor3 = Color3.new(1,0,0)
rif.BackgroundTransparency = 0.2
local to = Instance.new("SurfaceGui",plr.Character["Left Leg"])
local tof = Instance.new("Frame",to)
to.Face = "Top"
to.AlwaysOnTop = true
tof.Size = UDim2.new(1,0,1,0)
tof.BorderSizePixel = 0
tof.BackgroundColor3 = Color3.new(1,0,0)
tof.BackgroundTransparency = 0.2
local bo = Instance.new("SurfaceGui",plr.Character["Left Leg"])
local bof = Instance.new("Frame",bo)
bo.Face = "Bottom"
bo.AlwaysOnTop = true
bof.Size = UDim2.new(1,0,1,0)
bof.BorderSizePixel = 0
bof.BackgroundColor3 = Color3.new(1,0,0)
bof.BackgroundTransparency = 0.2
end
function rightle(plr)
local fr = Instance.new("SurfaceGui",plr.Character["Right Leg"])
local frf = Instance.new("Frame",fr)
fr.Face = "Front"
fr.AlwaysOnTop = true
frf.Size = UDim2.new(1,0,1,0)
frf.BorderSizePixel = 0
frf.BackgroundColor3 = Color3.new(1,0,0)
frf.BackgroundTransparency = 0.2
local ba = Instance.new("SurfaceGui",plr.Character["Right Leg"])
local baf = Instance.new("Frame",ba)
ba.Face = "Back"
ba.AlwaysOnTop = true
baf.Size = UDim2.new(1,0,1,0)
baf.BorderSizePixel = 0
baf.BackgroundColor3 = Color3.new(1,0,0)
baf.BackgroundTransparency = 0.2 
local le = Instance.new("SurfaceGui",plr.Character["Right Leg"])
local lef = Instance.new("Frame",le)
le.Face = "Left"
le.AlwaysOnTop = true
lef.Size = UDim2.new(1,0,1,0)
lef.BorderSizePixel = 0
lef.BackgroundColor3 = Color3.new(1,0,0)
lef.BackgroundTransparency = 0.2
local ri = Instance.new("SurfaceGui",plr.Character["Right Leg"])
local rif = Instance.new("Frame",ri)
ri.Face = "Right"
ri.AlwaysOnTop = true
rif.Size = UDim2.new(1,0,1,0)
rif.BorderSizePixel = 0
rif.BackgroundColor3 = Color3.new(1,0,0)
rif.BackgroundTransparency = 0.2
local to = Instance.new("SurfaceGui",plr.Character["Right Leg"])
local tof = Instance.new("Frame",to)
to.Face = "Top"
to.AlwaysOnTop = true
tof.Size = UDim2.new(1,0,1,0)
tof.BorderSizePixel = 0
tof.BackgroundColor3 = Color3.new(1,0,0)
tof.BackgroundTransparency = 0.2
local bo = Instance.new("SurfaceGui",plr.Character["Right Leg"])
local bof = Instance.new("Frame",bo)
bo.Face = "Bottom"
bo.AlwaysOnTop = true
bof.Size = UDim2.new(1,0,1,0)
bof.BorderSizePixel = 0
bof.BackgroundColor3 = Color3.new(1,0,0)
bof.BackgroundTransparency = 0.2
end
function hea(plr)
local fr = Instance.new("SurfaceGui",plr.Character.Head)
local frf = Instance.new("Frame",fr)
fr.Face = "Front"
fr.AlwaysOnTop = true
frf.Size = UDim2.new(1,0,1,0)
frf.BorderSizePixel = 0
frf.BackgroundColor3 = Color3.new(1,0,0)
frf.BackgroundTransparency = 0.2
local ba = Instance.new("SurfaceGui",plr.Character.Head)
local baf = Instance.new("Frame",ba)
ba.Face = "Back"
ba.AlwaysOnTop = true
baf.Size = UDim2.new(1,0,1,0)
baf.BorderSizePixel = 0
baf.BackgroundColor3 = Color3.new(1,0,0)
baf.BackgroundTransparency = 0.2 
local le = Instance.new("SurfaceGui",plr.Character.Head)
local lef = Instance.new("Frame",le)
le.Face = "Left"
le.AlwaysOnTop = true
lef.Size = UDim2.new(1,0,1,0)
lef.BorderSizePixel = 0
lef.BackgroundColor3 = Color3.new(1,0,0)
lef.BackgroundTransparency = 0.2
local ri = Instance.new("SurfaceGui",plr.Character.Head)
local rif = Instance.new("Frame",ri)
ri.Face = "Right"
ri.AlwaysOnTop = true
rif.Size = UDim2.new(1,0,1,0)
rif.BorderSizePixel = 0
rif.BackgroundColor3 = Color3.new(1,0,0)
rif.BackgroundTransparency = 0.2
local to = Instance.new("SurfaceGui",plr.Character.Head)
local tof = Instance.new("Frame",to)
to.Face = "Top"
to.AlwaysOnTop = true
tof.Size = UDim2.new(1,0,1,0)
tof.BorderSizePixel = 0
tof.BackgroundColor3 = Color3.new(1,0,0)
tof.BackgroundTransparency = 0.2
local bo = Instance.new("SurfaceGui",plr.Character.Head)
local bof = Instance.new("Frame",bo)
bo.Face = "Bottom"
bo.AlwaysOnTop = true
bof.Size = UDim2.new(1,0,1,0)
bof.BorderSizePixel = 0
bof.BackgroundColor3 = Color3.new(1,0,0)
bof.BackgroundTransparency = 0.2
end
------------------------------------------------------------------------------------------------------------------------



function ttors(plr)
local fr = Instance.new("SurfaceGui",plr.Character.Torso)
local frf = Instance.new("Frame",fr)
fr.Face = "Front"
fr.AlwaysOnTop = true
frf.Size = UDim2.new(1,0,1,0)
frf.BorderSizePixel = 0
frf.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
frf.BackgroundTransparency = 0.2
local ba = Instance.new("SurfaceGui",plr.Character.Torso)
local baf = Instance.new("Frame",ba)
ba.Face = "Back"
ba.AlwaysOnTop = true
baf.Size = UDim2.new(1,0,1,0)
baf.BorderSizePixel = 0
baf.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
baf.BackgroundTransparency = 0.2 
local le = Instance.new("SurfaceGui",plr.Character.Torso)
local lef = Instance.new("Frame",le)
le.Face = "Left"
le.AlwaysOnTop = true
lef.Size = UDim2.new(1,0,1,0)
lef.BorderSizePixel = 0
lef.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
lef.BackgroundTransparency = 0.2
local ri = Instance.new("SurfaceGui",plr.Character.Torso)
local rif = Instance.new("Frame",ri)
ri.Face = "Right"
ri.AlwaysOnTop = true
rif.Size = UDim2.new(1,0,1,0)
rif.BorderSizePixel = 0
rif.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
rif.BackgroundTransparency = 0.2
local to = Instance.new("SurfaceGui",plr.Character.Torso)
local tof = Instance.new("Frame",to)
to.Face = "Top"
to.AlwaysOnTop = true
tof.Size = UDim2.new(1,0,1,0)
tof.BorderSizePixel = 0
tof.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
tof.BackgroundTransparency = 0.2
local bo = Instance.new("SurfaceGui",plr.Character.Torso)
local bof = Instance.new("Frame",bo)
bo.Face = "Bottom"
bo.AlwaysOnTop = true
bof.Size = UDim2.new(1,0,1,0)
bof.BorderSizePixel = 0
bof.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
bof.BackgroundTransparency = 0.2
end
function trightar(plr)
local fr = Instance.new("SurfaceGui",plr.Character["Right Arm"])
local frf = Instance.new("Frame",fr)
fr.Face = "Front"
fr.AlwaysOnTop = true
frf.Size = UDim2.new(1,0,1,0)
frf.BorderSizePixel = 0
frf.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
frf.BackgroundTransparency = 0.2
local ba = Instance.new("SurfaceGui",plr.Character["Right Arm"])
local baf = Instance.new("Frame",ba)
ba.Face = "Back"
ba.AlwaysOnTop = true
baf.Size = UDim2.new(1,0,1,0)
baf.BorderSizePixel = 0
baf.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
baf.BackgroundTransparency = 0.2 
local le = Instance.new("SurfaceGui",plr.Character["Right Arm"])
local lef = Instance.new("Frame",le)
le.Face = "Left"
le.AlwaysOnTop = true
lef.Size = UDim2.new(1,0,1,0)
lef.BorderSizePixel = 0
lef.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
lef.BackgroundTransparency = 0.2
local ri = Instance.new("SurfaceGui",plr.Character["Right Arm"])
local rif = Instance.new("Frame",ri)
ri.Face = "Right"
ri.AlwaysOnTop = true
rif.Size = UDim2.new(1,0,1,0)
rif.BorderSizePixel = 0
rif.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
rif.BackgroundTransparency = 0.2
local to = Instance.new("SurfaceGui",plr.Character["Right Arm"])
local tof = Instance.new("Frame",to)
to.Face = "Top"
to.AlwaysOnTop = true
tof.Size = UDim2.new(1,0,1,0)
tof.BorderSizePixel = 0
tof.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
tof.BackgroundTransparency = 0.2
local bo = Instance.new("SurfaceGui",plr.Character["Right Arm"])
local bof = Instance.new("Frame",bo)
bo.Face = "Bottom"
bo.AlwaysOnTop = true
bof.Size = UDim2.new(1,0,1,0)
bof.BorderSizePixel = 0
bof.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
bof.BackgroundTransparency = 0.2
end
function tleftar(plr)
local fr = Instance.new("SurfaceGui",plr.Character["Left Arm"])
local frf = Instance.new("Frame",fr)
fr.Face = "Front"
fr.AlwaysOnTop = true
frf.Size = UDim2.new(1,0,1,0)
frf.BorderSizePixel = 0
frf.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
frf.BackgroundTransparency = 0.2
local ba = Instance.new("SurfaceGui",plr.Character["Left Arm"])
local baf = Instance.new("Frame",ba)
ba.Face = "Back"
ba.AlwaysOnTop = true
baf.Size = UDim2.new(1,0,1,0)
baf.BorderSizePixel = 0
baf.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
baf.BackgroundTransparency = 0.2 
local le = Instance.new("SurfaceGui",plr.Character["Left Arm"])
local lef = Instance.new("Frame",le)
le.Face = "Left"
le.AlwaysOnTop = true
lef.Size = UDim2.new(1,0,1,0)
lef.BorderSizePixel = 0
lef.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
lef.BackgroundTransparency = 0.2
local ri = Instance.new("SurfaceGui",plr.Character["Left Arm"])
local rif = Instance.new("Frame",ri)
ri.Face = "Right"
ri.AlwaysOnTop = true
rif.Size = UDim2.new(1,0,1,0)
rif.BorderSizePixel = 0
rif.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
rif.BackgroundTransparency = 0.2
local to = Instance.new("SurfaceGui",plr.Character["Left Arm"])
local tof = Instance.new("Frame",to)
to.Face = "Top"
to.AlwaysOnTop = true
tof.Size = UDim2.new(1,0,1,0)
tof.BorderSizePixel = 0
tof.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
tof.BackgroundTransparency = 0.2
local bo = Instance.new("SurfaceGui",plr.Character["Left Arm"])
local bof = Instance.new("Frame",bo)
bo.Face = "Bottom"
bo.AlwaysOnTop = true
bof.Size = UDim2.new(1,0,1,0)
bof.BorderSizePixel = 0
bof.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
bof.BackgroundTransparency = 0.2
end
function tleftle(plr)
local fr = Instance.new("SurfaceGui",plr.Character["Left Leg"])
local frf = Instance.new("Frame",fr)
fr.Face = "Front"
fr.AlwaysOnTop = true
frf.Size = UDim2.new(1,0,1,0)
frf.BorderSizePixel = 0
frf.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
frf.BackgroundTransparency = 0.2
local ba = Instance.new("SurfaceGui",plr.Character["Left Leg"])
local baf = Instance.new("Frame",ba)
ba.Face = "Back"
ba.AlwaysOnTop = true
baf.Size = UDim2.new(1,0,1,0)
baf.BorderSizePixel = 0
baf.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
baf.BackgroundTransparency = 0.2 
local le = Instance.new("SurfaceGui",plr.Character["Left Leg"])
local lef = Instance.new("Frame",le)
le.Face = "Left"
le.AlwaysOnTop = true
lef.Size = UDim2.new(1,0,1,0)
lef.BorderSizePixel = 0
lef.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
lef.BackgroundTransparency = 0.2
local ri = Instance.new("SurfaceGui",plr.Character["Left Leg"])
local rif = Instance.new("Frame",ri)
ri.Face = "Right"
ri.AlwaysOnTop = true
rif.Size = UDim2.new(1,0,1,0)
rif.BorderSizePixel = 0
rif.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
rif.BackgroundTransparency = 0.2
local to = Instance.new("SurfaceGui",plr.Character["Left Leg"])
local tof = Instance.new("Frame",to)
to.Face = "Top"
to.AlwaysOnTop = true
tof.Size = UDim2.new(1,0,1,0)
tof.BorderSizePixel = 0
tof.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
tof.BackgroundTransparency = 0.2
local bo = Instance.new("SurfaceGui",plr.Character["Left Leg"])
local bof = Instance.new("Frame",bo)
bo.Face = "Bottom"
bo.AlwaysOnTop = true
bof.Size = UDim2.new(1,0,1,0)
bof.BorderSizePixel = 0
bof.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
bof.BackgroundTransparency = 0.2
end
function trightle(plr)
local fr = Instance.new("SurfaceGui",plr.Character["Right Leg"])
local frf = Instance.new("Frame",fr)
fr.Face = "Front"
fr.AlwaysOnTop = true
frf.Size = UDim2.new(1,0,1,0)
frf.BorderSizePixel = 0
frf.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
frf.BackgroundTransparency = 0.2
local ba = Instance.new("SurfaceGui",plr.Character["Right Leg"])
local baf = Instance.new("Frame",ba)
ba.Face = "Back"
ba.AlwaysOnTop = true
baf.Size = UDim2.new(1,0,1,0)
baf.BorderSizePixel = 0
baf.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
baf.BackgroundTransparency = 0.2 
local le = Instance.new("SurfaceGui",plr.Character["Right Leg"])
local lef = Instance.new("Frame",le)
le.Face = "Left"
le.AlwaysOnTop = true
lef.Size = UDim2.new(1,0,1,0)
lef.BorderSizePixel = 0
lef.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
lef.BackgroundTransparency = 0.2
local ri = Instance.new("SurfaceGui",plr.Character["Right Leg"])
local rif = Instance.new("Frame",ri)
ri.Face = "Right"
ri.AlwaysOnTop = true
rif.Size = UDim2.new(1,0,1,0)
rif.BorderSizePixel = 0
rif.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
rif.BackgroundTransparency = 0.2
local to = Instance.new("SurfaceGui",plr.Character["Right Leg"])
local tof = Instance.new("Frame",to)
to.Face = "Top"
to.AlwaysOnTop = true
tof.Size = UDim2.new(1,0,1,0)
tof.BorderSizePixel = 0
tof.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
tof.BackgroundTransparency = 0.2
local bo = Instance.new("SurfaceGui",plr.Character["Right Leg"])
local bof = Instance.new("Frame",bo)
bo.Face = "Bottom"
bo.AlwaysOnTop = true
bof.Size = UDim2.new(1,0,1,0)
bof.BorderSizePixel = 0
bof.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
bof.BackgroundTransparency = 0.2
end
function thea(plr)
local fr = Instance.new("SurfaceGui",plr.Character.Head)
local frf = Instance.new("Frame",fr)
fr.Face = "Front"
fr.AlwaysOnTop = true
frf.Size = UDim2.new(1,0,1,0)
frf.BorderSizePixel = 0
frf.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
frf.BackgroundTransparency = 0.2
local ba = Instance.new("SurfaceGui",plr.Character.Head)
local baf = Instance.new("Frame",ba)
ba.Face = "Back"
ba.AlwaysOnTop = true
baf.Size = UDim2.new(1,0,1,0)
baf.BorderSizePixel = 0
baf.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
baf.BackgroundTransparency = 0.2 
local le = Instance.new("SurfaceGui",plr.Character.Head)
local lef = Instance.new("Frame",le)
le.Face = "Left"
le.AlwaysOnTop = true
lef.Size = UDim2.new(1,0,1,0)
lef.BorderSizePixel = 0
lef.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
lef.BackgroundTransparency = 0.2
local ri = Instance.new("SurfaceGui",plr.Character.Head)
local rif = Instance.new("Frame",ri)
ri.Face = "Right"
ri.AlwaysOnTop = true
rif.Size = UDim2.new(1,0,1,0)
rif.BorderSizePixel = 0
rif.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
rif.BackgroundTransparency = 0.2
local to = Instance.new("SurfaceGui",plr.Character.Head)
local tof = Instance.new("Frame",to)
to.Face = "Top"
to.AlwaysOnTop = true
tof.Size = UDim2.new(1,0,1,0)
tof.BorderSizePixel = 0
tof.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
tof.BackgroundTransparency = 0.2
local bo = Instance.new("SurfaceGui",plr.Character.Head)
local bof = Instance.new("Frame",bo)
bo.Face = "Bottom"
bo.AlwaysOnTop = true
bof.Size = UDim2.new(1,0,1,0)
bof.BorderSizePixel = 0
bof.BackgroundColor3 = Color3.new(0/255, 255/255, 255/255)
bof.BackgroundTransparency = 0.2
end
while true do
wait(0.1)
for _, v in pairs(plrs:GetChildren()) do
if v.TeamColor ~= plrs.LocalPlayer.TeamColor and not v.Character.Torso:FindFirstChild("SurfaceGui") then --   ~= 
tors(v)
rightar(v)
leftar(v)
leftle(v)
rightle(v)
hea(v)
end
if v.TeamColor == plrs.LocalPlayer.TeamColor and v.Name ~= plrs.LocalPlayer.Name and not v.Character.Torso:FindFirstChild("SurfaceGui") then --   ~= 
ttors(v)
trightar(v)
tleftar(v)
tleftle(v)
trightle(v)
thea(v)
end
end
end